// Code generated by some tool. DO NOT EDIT.

package filefilter

import (
	"context"
	"fmt"
)

// badGoroutineInGenerated would normally be reported, but generated files are always skipped.
func badGoroutineInGenerated(ctx context.Context) {
	go func() {
		fmt.Println("no context in generated file")
	}()
}
