// Code generated by some tool. DO NOT EDIT.

// Package linedirectivegen tests that //line directives do not change which
// files are generated.
package linedirectivegen

import "context"

//line fake.tmpl:1
func badGoroutineInGenerated(ctx context.Context) {
	go func() {}()
}
